services:
  _defaults:
    autowire: true
    public: false

  PrestaShop\PrestaShop\Core\ExtraProperty\Grid\ExtraPropertiesGridDefinitionModifier:
    arguments:
      $repository: '@PrestaShop\PrestaShop\Core\ExtraProperty\Definition\ExtraPropertyDefinitionRepositoryInterface'
      $translator: '@translator'
      $shopContext: '@PrestaShop\PrestaShop\Core\Context\ShopContext'

  PrestaShop\PrestaShop\Core\ExtraProperty\Grid\ExtraPropertiesGridQueryBuilderModifier:
    arguments:
      $repository: '@PrestaShop\PrestaShop\Core\ExtraProperty\Definition\ExtraPropertyDefinitionRepositoryInterface'
      $dbPrefix: '%database_prefix%'
      $contextLangId: '@=service("prestashop.adapter.legacy.context").getContext().language.id'
